var questions = [["What is the supreme law of the land?", "The Constitution"],
["What does the Constitution do?", "* Sets up the government \n* Defines the governemnt \n* Protects basic rights of Americans"],
["The idea of self-government is in the first three words of the Constitution. What are these words?", "We the People"],
["What is an amendment?", "* A Change (to the Constitution) \n* An addition (to the Constitution)"],
["What do we call the first ten amendments to the Constitution?", "The Bill of Rights"],
["What is one right or freedom from the First Amendment?" , "* Speech \n* Religion \n* Assembly \n* Press \n* Petition the governemnt"],
["How many amendments does the Constitution have?", "Twenty-seven (27)"],
["What did the Declaration of Independence do?", "* Announced our independence (from Great Britain) \n* Declared our independence (from Great Britain) \n* Said that the United States is free (from Great Britain)"],
["What are two rights in the Declaration of Independence?", "* Life \n* Liberty \n* Pursuit of Happiness"],
["What is freedom of religion?", "You can practice any religion, or not practice a religion."],
["What is the economic system in the United States?", "* Capitalist economy \n* Market economy"],
["What is the 'rule of law?'", "* Everyone must follow the law \n* Leaders must obey the law \n* Government must obey the law \n* No one is above the law"],
["Name one branch or part of the governemnt", "* Congress \n* Legislative \n* President \n* Executive \n* The courts \n* Judicial"],
["What stops one branch of governemnt from becoming too powerful?", "* Checks and balances \n* Separation of powers"],
["Who is in charge of the executive branch?", "The President"],
["Who makes federal laws?", "* Congress \n* Senate and House (of Representatives) \n* (U.S. or national) legislature"],
["What are the two parts of the U.S. Congress?", "The Senate and House (of Representatives)"],
["How many U.S. Senators are there?", "One hundrer (100)"],
["We elect a U.S. Senator for how many years?", "Siz (6)"],
["Who is one of your State's U.S. Senators now?", "For New York: Chuck Schumer & Kirsten Gillibrand"],
["The House of Representatives has how many voting members?", "Four hundred thirty-five (435)"],
["We elect a U.S. Representatives for how many years?", "Two (2)"],
["Name your U.S. Representative", "Tim Bishop and many more"],
["Who does a U.S. Senator represent?", "All people of the state"],
["Why do some states have more Representatives than other states?", "* (Because of) the state's population \n* (Because) they have more people \n* (Because) some states have more people"],
["We elect a President for how many years?", "Four (4)"],
["In what month do we vote for Presidents?", "November"],
["What is the name of the President of the United States now?", "Barack Obama"],
["What is the name of the Vice President of the United States now?", "Joe Bidden"],
["If the President can no long serve, who becomes President?", "The Vice President"]];